### ISSUE TITLE
`beforeAll` hook not loaded

### ISSUE THREAD

**Issue by fredrikfoss** [nvim-neorocks/lz.n#100] opened 2024-10-15 11:09 UTC
Hi, I'm not sure I misunderstand how it should work, but the `beforeAll` hook doesn't seem to ever run? To reproduce:

```
return {
  'some.plugin',
  beforeAll = function()
    vim.notify('lz.n very cool, thanks for you work')
  end,
}
```

**Comment by mrcjkb** [comment] 2024-10-15 14:29
Hey :wave: 

Thanks for reporting and the nice notify :smile: :pray: 

It looks like I introduced a regression during a refactor. Will be fixed with #101.

**Closed** 2024-10-15 14:30 UTC
